### ISSUE TITLE
Address dependency management issues

### ISSUE THREAD

**Issue by notmessenger** [ciena-frost/ember-frost-core#520]
https://github.com/ciena-blueplanet/ember-spread/issues/37 **MUST** be completed before this issue.

    * remove from blueprints and make devDependency
        * ember-cli-frost-blueprints
        * ember-hook

    * remove from blueprints and make dependency
        * ember-prop-types
        * ember-spread
        * ember-computed-decorators
        * ember-concurrency
        * ember-elsewhere
        * ember-truth-helpers

    * update ember-prop-types to ^5.0.2
    * update ember-spread to ^3.0.1

**Comment by notmessenger** [comment]
https://github.com/ciena-frost/ember-cli-frost-blueprints/issues/19 **MUST** be resolved before this issue can be addressed.  Some of the individual tasks _may_ be able to be worked on before the completion of the dependent issue.  If doing so indicate which tasks have been completed by checking them off in the list below, as well as adding a comment to this issue indicating the name of the branch you have pushed to this repo so that work can completed once the dependent task has been addressed.

* Tasks that have the text _"(verified)"_ after them are ones that have either already been tested or are known to work.  This does not mean that you should not still be cautious but you likely don't have to do as much research as you might initially be inclinded to.
* None of the tasks make a determination of whether a dependency should be a **dependency** or **devDependency** _UNLESS_ otherwise stated.  Even then it is prudent to confirm this indicator.
* All dependencies should float to `^` unless the directions in the tasks indicate otherwise. The following entries are known items that should REMAIN pinned:
  * `markdown-code-highlighting`

**NPM**

* [x] determine whether frost-guide-customer-routing is needed
* [x] determine whether broccoli-autoprefixer is needed.  ^5.0.0 is latest (major)
* [x] determine whether broccoli-babel-transpiler is needed.  ^5.7.2 or ^6.1.2 (major) is latest
* [x] determine whether broccoli-file-creator is needed (think #521 will take care of this)
* [x] determine whether child-process-promise is needed (think #521 will take care of this)
* [x] determine whether ember-cli-path-utils is needed (think #521 will take care of this)
* [x] determine whether promise is needed (think #521 will take care of this)
* [x] determine whether semver is needed (think #521 will take care of this)
* [x] remove npm-install-security-check (verified)
* [x] determine whether ember-browserify is needed.  if so ^1.2.0 is latest (likely is - talk to @notmessenger)
* [x] `npm uninstall ember-frost-test` and `ember install ember-frost-test` (verified)
  * [x] `ember-cli-chai` will be updated to `0.4.3` so _may_ encounter issues
  * [x] `ember-cli-mocha` will be updated to `0.14.4` so _may_ encounter issues
  * [x] `ember-sinon` will be updated to `^0.7.0` so _may_ encounter issues
* [x] pin ember-computed-decorators to 0.3.0 (verified)
* [x] upgrade ember-cli-sass to pinned 7.1.1 (verified)
* [x] pin ember-hook to 1.4.2
* [x] determine whether ember-hook needs to be a **dependency**
* [x] pin ember-concurrency to 0.7.19 (verified)
* [x] update broccoli-merge-trees to ^2.0.0
* [x] update broccoli-funnel to ^2.0.1
* [x] remove frost-guide-custom-routing
* [x] update ember-prop-types to ^6.0.0 (or whatever the latest release is)
* [x] update ember-spread to ^4.0.1
* [x] keep `ember-code-snippet` at current version
* [x] update or install ember-cli-frost-blueprints to ^5.0.1
* [x] remove `useLintTree` from `ember-cli-mocha` configuration in _ember-cli-build.js_
* [x] make `chalk` a **dependency** at `^2.3.0` _...however..._ this is only needed until #521 is resolved which will be on the heels of this issue so can maybe skip too
* [x] determine **dependencies** vs **devDependencies**

**BOWER**
* [x] pin ember-inflector to 1.3.1
* [x] pin highlightjs to 9.12.0
* [x] move Faker to **devDependencies** of _bower.json_
* [x] move pretender to **devDependencies** of _bower.json_

**Comment by notmessenger** [comment]
JIRA: FROST-584

**Comment by notmessenger** [comment]
In-progress changes have been pushed to the github.com/notmessenger/ember-frost-core#Issue520 branch.

Before PR can be opened as a **???** against the github.com/notmessenger/ember-frost-core#Issue520 branch:

* [x] `ember-frost-test@4.0.0` must be released
  * https://github.com/ciena-frost/ember-frost-test/pull/42
* [x] `ember-prop-types@6.0.1` must be released
  * https://github.com/ciena-blueplanet/ember-prop-types/issues/153
* [x] `ember-spread@4.0.1` must be released
  * https://github.com/ciena-blueplanet/ember-spread/issues/37
* [x] `ember-cli-frost-blueprints@5.0.1` must be released
  * https://github.com/ciena-frost/ember-cli-frost-blueprints/issues/19
* [x] These changes must be tested in a consuming add-on and application
